### ISSUE TITLE
Timed interval/tick?

### ISSUE THREAD

**Issue by woubuc** [DavidBM/acteur-rs#2]
What is the best way to implement a 'tick' in some actors?

I'm playing around with Acteur for the backend for a multiplayer game. A lot of the actors only need to respond when a player interacts with it, so a full ECS that runs everything constantly would be overkill. But there are a set of actors that do need to be updated every tick (e.g. 20 times per second). Think of a Minecraft world where a lot of things just "stand around" (like doors and tables and torches) but there are also animals and mobs that need to move on each game tick.

Does Acteur have a built-in feature to call a function on an actor in a timed interval, or what would be the advised way to handle this? Should I just keep a timer outside of Acteur and send a 'tick' message to the actors every time?

**Comment by DavidBM** [comment]
I didn't think about timed simulation yet.

I guess the best way would be to have a thread sending messages for every tick to all actors. You can use a service in order to keep track of the actors that need to be receiving that message. I can think in, for example, Service "Animal" which handles a message "tick" and a message "subscribe_to_tick". 

- subscribe_to_tick just takes the ID of the actors and stores it (the actor can send a message to the service when created and you would need one message in order to unsubscribe too)
- tick would just take all subscribed actors and send them the message "tick".

That for now. We could implement a "send all" message for the actors where you can send a message too all actors of a type, which would simplify things. 

Still, I want to warn you a bit about expectations. ECS and Actors work very differently. With ECS you can create a deterministic simulation, with actors it may be much more complex. My idea for a game with actors was more like an slow pace online game, where the time synchronization is not so important. With actors you may end having actors that have a delay of several ticks just because they had more messages to process (lets say a mod that is fighting). It would be hard and latency expensive to keep everything synchronized. If that is not a problem for you, then actors may be the way to go :)

If you want to continue using Acteur I can implement the send_all method for you, so that you can just have a thread calling that method in all entities that need to be subscribed. Or, I can make something like "enqueue_message_to_myself_in_time" function (name would change, but you get the idea).

Let me know!

**Comment by woubuc** [comment]
Thanks for your response! I will give the subscriptions method a try.

> ECS and Actors work very differently. With ECS you can create a deterministic simulation, with actors it may be much more complex. My idea for a game with actors was more like an slow pace online game, where the time synchronization is not so important.

This was a consideration I had as well. I would like to use an actor system for everything surrounding the core game tick and I'm evaluating if the actor system will work for the tick as well. I'm working on a sandbox building game prototype with this, so not an FPS where every millisecond counts, so it's quite possible that it will work out just fine. But I will need to test the performance of course. Otherwise I will have to look into combining both systems in some way.

> We could implement a "send all" message for the actors where you can send a message too all actors of a type

I think that would be very useful for many purposes. Apart from my use case, I can see for instance a websocket server where every open connection/session is an actor, and you want to broadcast a message to all of them.

Possibly there could be two variants of this function: "call/send to all actors of a type" and "call/send to all actors that accept this message type" (I don't know if it would be feasible to implement the latter though).

> something like "enqueue_message_to_myself_in_time" function

Built-in timers also seem very useful. I would imagine it would include both a `delay` (once) and an `interval` (repeated).

**Comment by DavidBM** [comment]
The "call/send to all actors that accept this message type" may be not possible as it would require runtime reflection. Right now I'm using the TypeId in order to route the message to the correct actor family, which forces the framework to save the typeId on the first message. That works because you have the actor type and the actor message on the call, so if you use a wrong combination of actor and message, it won't compile. The message thing would be 100% runtime. 

For that maybe it should be better to write a service and use the pub sub method. The idea would be for the service to know to what actors the message should be sent.

I will implement the method for sending to all actors. I don't think calling all actors would be possible, as I would need to wait for the responses of all actors, which would require a lot of coordination and ram (Imagine if you have 20.000 actors, that would be a 20000 responses in Ram).

I think I will make another family of functions for sending messages after some timeout.

**Comment by DavidBM** [comment]
So, I have just pushed a new version that adds:

schedule_send_to_actor
send_to_all_actors
schedule_send_to_all_actors

for actors, services and the main Acteur object.

I hope that helps, let me know if you find another corner case!

There is one important catch. The send all won't activate an actor that is not loaded, it will only send the message to the already loaded actors. Maybe next I should give more options for controlling when actors are cleaned out from Ram if they are not used. now it is 5 minutes.

**Comment by woubuc** [comment]
Awesome work, thanks! I think that about covers it for my use case right now.

**Comment by DavidBM** [comment]
@woubuc  I wanted to check if you are still using acteur. Does it work for you use case?

**Comment by woubuc** [comment]
My initial experiments with Acteur were successful, but I didn't end up continuing with this particular project because of other things demanding more time (as happens too often with side projects). I intend to use Acteur for other projects in the future though.

**Comment by DavidBM** [comment]
Nice! Let me know when you do! I valuate a lot people using it in order to find real usage patterns
