### ISSUE TITLE
How to handle failures during Actor activation / Service initialization

### ISSUE THREAD

**Issue by mneumann** [DavidBM/acteur-rs#3]
Is it best to `panic` and let _Acteur_ deal with the problem? For example, I want to setup a database connection in a service, which might fail. Obviously, that would be a fatal error and I would abort anyway. Just curious about the best practices.

**Comment by DavidBM** [comment]
Hi! That is a good question! 

For that, I would activate the services on start and if some of them fail I would just let the app crash (a panic is ok if you want to crash the app anyway).

For actors, definitively you shouldn't have any fallible operation on start! And the reason for that is that you may want to implement logic for that failure and provably you will want something different from what the framework may do. Mostly, because when you send the first message to the actor, you don't have any failure response saying "the actor failed to start, so handle the case with a match".

I would put all things that can fail in services and leave the actors for pure business logic where all fallible cases can be handled. Or fallible cases need to be on messages where there is a response with a chance to recover the error. 

In any case, actors shouldn't be failing and if they do they should have the chance to respond to the message or to inform some service of the failure. 

Imagine this case:

An actor needs to send something to the DB, so you program it with access to an Arc<Mutex<DbConnection>>. The actor try to send the INSERT to the DB, but the connection breaks, so now you have an actor that failed and no way to handle the error because who sent you the message assumes the actor was able to do their job. I see two ways to handle this:

1) (My favorite) You put a service between actors and the DB and let the service store queries in ram. If the connection breaks try to send them again when the connection reopens. Or you can just panic if you tried to reopen it after several tries. Moreover, this allows you to control how much concurrency you have over the connection and at the same time makes easier to implement recovery strategies (with actors you may have potentially infinite concurrency). This works much better if you can have idempotent queries like "save the whole actor state in DB".

2) (Don't like it, but may apply on some cases) When the actor fails, you send a message to a service in order to inform that something failed. On this service you can choose to panic or to try to solve the connection problem. Maybe by creating a new connection and sending it to the actors.

**Comment by mneumann** [comment]
What you say makes a lot of sense!

Concerning failures during actor initialization: 

In Pony (ponylang.io), actor constructors can't fail, because the constructor code runs asynchronously to the creator in the actors context.

On the other hand Actix and Xactor separate the actor initialization from starting the actor. Initialization here just uses Rust's struct initialization, no framework method is used. Obviously, the code that initializes the struct and then starts an actor has the full power and can handle possible failures. In Acteur of course we could do the same by "partial" initializing the Actor using an `Option` and then reporting the error when a message is sent. But I would rather not do it this way. Instead, as you said, use a Service and preload it. 

For now I am using a service, preload it and just panic in case of an error.

**Comment by DavidBM** [comment]
Nice! 

Keep in mind that you should be able to do the same via an initialization method that cannot fail and sets the values to None. The main issue here is that in Acteur is the Framework who controls the lifecycle.

**Comment by DavidBM** [comment]
Btw, Can I know what is your use case for Acteur @mneumann ?
